tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container-highest": "#eae0e0",
                "tertiary-fixed-dim": "#d7c2c1",
                "surface-container-high": "#efe6e5",
                "on-error": "#ffffff",
                "secondary-container": "#f5dddd",
                "on-tertiary-fixed": "#241919",
                "surface-tint": "#7c5454",
                "on-secondary-container": "#726060",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed-variant": "#534343",
                "on-primary-fixed-variant": "#613d3d",
                "inverse-surface": "#342f2f",
                "tertiary-fixed": "#f3dddd",
                "error-container": "#ffdad6",
                "error": "#ba1a1a",
                "outline-variant": "#d4c2c2",
                "surface-variant": "#eae0e0",
                "background": "#fff8f7",
                "secondary-fixed": "#f5dddd",
                "primary-container": "#d4a3a3",
                "on-tertiary-fixed-variant": "#524343",
                "on-secondary-fixed": "#251819",
                "primary-fixed-dim": "#edbaba",
                "on-tertiary-container": "#4d3f3f",
                "on-error-container": "#93000a",
                "on-primary-container": "#5c3939",
                "surface-container-low": "#fbf1f1",
                "outline": "#827473",
                "surface-dim": "#e1d8d7",
                "surface-container": "#f5eceb",
                "on-surface-variant": "#504444",
                "tertiary": "#6b5b5b",
                "on-primary": "#ffffff",
                "inverse-on-surface": "#f8efee",
                "on-primary-fixed": "#2f1314",
                "on-surface": "#1f1b1a",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "secondary-fixed-dim": "#d8c1c1",
                "primary": "#7c5454",
                "surface": "#fff8f7",
                "tertiary-container": "#beaaaa",
                "inverse-primary": "#edbaba",
                "on-background": "#1f1b1a",
                "surface-bright": "#fff8f7",
                "secondary": "#6b5a5b",
                "primary-fixed": "#ffdad9"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "unit": "8px",
                "stack-lg": "5rem",
                "stack-md": "2.5rem",
                "margin-mobile": "20px",
                "gutter": "24px",
                "container-max": "1280px",
                "margin-desktop": "64px",
                "stack-sm": "1rem"
            },
            "fontFamily": {
                "headline-lg-mobile": ["Playfair Display"],
                "body-lg": ["Source Serif 4"],
                "headline-md": ["Playfair Display"],
                "label-sm": ["Manrope"],
                "headline-lg": ["Playfair Display"],
                "display-lg": ["Playfair Display"],
                "body-md": ["Source Serif 4"]
            },
            "fontSize": {
                "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "headline-md": ["28px", { "lineHeight": "1.3", "fontWeight": "500" }],
                "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
                "headline-lg": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
            }
        },
    },
}
